mobs:
  BAT: true
  BLAZE: true
  CAT: true
  CAVE_SPIDER: true
  CHICKEN: true
  COD: true
  COW: true
  CREEPER: true
  DOLPHIN: true
  DONKEY: true
  DROWNED: true
  ENDER_DRAGON: true
  ENDERMAN: true
  ENDERMITE: true
  FOX: true
  GHAST: true
  GUARDIAN: true
  PANDA: true
  PIG: true
  PIG_ZOMBIE: true
  POLAR_BEAR: true
  SALMON: true
  SHEEP: true
  SKELETON: true
  SPIDER: true
  SQUID: true
  TURTLE: true
  WITCH: true
  WITHER: true
  WOLF: true
  ZOMBIE: true